import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split('''
pubsub_c.c
''')

if GetDepend(['PS_QUEUE_BUCKET']):
    src += ['ps_queue_bucket.c']

if GetDepend(['PS_QUEUE_LL']):
    src += ['ps_queue_ll.c']

if GetDepend(['PS_SYNC_RTTHREAD']):
    src += ['sync_rtthread.c']

group = DefineGroup('pubsub-c', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
